<?php


namespace rickcy\tarantool\tests;


use rickcy\tarantool\ActiveRecord;

class User extends ActiveRecord
{

    public $id = null;
    public $guid;
    public $email;
    public $name;
    public $surname;
    public $middle_name;


    public static function tableName(): string
    {
        return 'users'; // TODO: Change the autogenerated stub
    }


    /**
     * @return array
     */
    public static function getColumns() : array
    {
        return ['id', 'guid', 'email', 'name', 'surname', 'middle_name'];
    }

    /**
     * @return array
     */
    public function attributes() : array
    {
        return self::getColumns();
    }

}