<?php


namespace rickcy\tarantool\tests;


use rickcy\tarantool\ActiveRecord;

class User extends ActiveRecord
{

    public $id;
    public $guid;
    public $email;
    public $name;
    public $surname;
    public $middle__name;


    public static function tableName() : string
    {
        return 'users'; // TODO: Change the autogenerated stub
    }


    public static function getColumns()
    {
        ['id', 'guid', 'email', 'name', 'surname', 'middle_name'];
    }
}